# Visit https://github.com/lowlighter/metrics#-documentation for full reference
name: Metrics
on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 0 * * *"}]
  workflow_dispatch:
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          # Options
          template: markdown
          filename: README.md
          base: header, repositories, metadata
          base_hireable: yes
          config_timezone: America/New_York
          repositories_affiliations: owner, collaborator
          plugin_languages: yes
          plugin_repositories: yes
          # Temporary fix for lowlighter/metrics#1222
          extras_css: |
            .field.warning { display: none; }
